import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  LayoutAnimation,
  Platform,
  UIManager,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Sparkles, TrendingDown, TrendingUp, Target, CheckCircle, Circle, Zap, Clock, AlertCircle } from 'lucide-react-native';
import { useFinance } from '@/contexts/FinanceContext';
import { AppColors } from '@/constants/colors';
import type { OptimizationSuggestion } from '@/constants/types';
import { fontFamily } from '@/constants/Typography';
import { BlueGlow } from '@/components/BlueGlow';
import { LinearGradient } from 'expo-linear-gradient';

if (Platform.OS === 'android') {
  if (UIManager.setLayoutAnimationEnabledExperimental) {
    UIManager.setLayoutAnimationEnabledExperimental(true);
  }
}

export default function OptimizerScreen() {
  const insets = useSafeAreaInsets();
  const { 
    optimizations, 
    isOptimizing, 
    generateOptimizations, 
    markOptimizationImplemented,
    transactions,
  } = useFinance();
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [report, setReport] = useState<{ totalSavings: number; totalIncome: number } | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (optimizations.length > 0) {
      const totalSavings = optimizations.reduce((sum, opt) => sum + (opt.potentialSavings || 0), 0);
      const totalIncome = optimizations.reduce((sum, opt) => sum + (opt.potentialIncome || 0), 0);
      setReport({ totalSavings, totalIncome });
    }
  }, [optimizations]);

  useEffect(() => {
    const autoGenerate = async () => {
      if (transactions.length === 0) return;

      try {
        const result = await generateOptimizations();
        setReport({
          totalSavings: result.totalPotentialSavings,
          totalIncome: result.totalPotentialIncome,
        });
      } catch (error) {
        console.error('Auto-generation failed:', error);
      }
    };

    if (!hasAutoGenerated && !isOptimizing && transactions.length > 0 && optimizations.length === 0) {
      console.log('Auto-generating initial optimizations...');
      setHasAutoGenerated(true);
      autoGenerate();
    }
  }, [transactions.length, optimizations.length, hasAutoGenerated, isOptimizing, generateOptimizations]);

  const handleOptimize = async () => {
    if (transactions.length === 0) {
      Alert.alert('No Data', 'Please add some transactions first to get optimization suggestions.');
      return;
    }

    try {
      const result = await generateOptimizations();
      setReport({
        totalSavings: result.totalPotentialSavings,
        totalIncome: result.totalPotentialIncome,
      });
    } catch {
      Alert.alert('Error', 'Failed to generate optimizations. Please try again.');
    }
  };

  const toggleExpand = (id: string) => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setExpandedIds(prev => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  const handleMarkImplemented = (id: string) => {
    Alert.alert(
      'Mark as Implemented',
      'Have you implemented this optimization?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Yes',
          onPress: () => markOptimizationImplemented(id),
        },
      ]
    );
  };

  const expenseReductions = optimizations.filter(o => o.type === 'expense_reduction');
  const incomeIncreases = optimizations.filter(o => o.type === 'income_increase');
  const savingsBoosts = optimizations.filter(o => o.type === 'savings_boost');
  const investments = optimizations.filter(o => o.type === 'investment_opportunity');

  return (
    <View style={styles.container}>
      <BlueGlow />
      <View style={[styles.contentContainer, { paddingTop: insets.top }]}>
        <View style={styles.header}>
          <View>
            <Text style={styles.headerTitle}>AI Optimizer</Text>
            <Text style={styles.headerSubtitle}>Maximize savings & income</Text>
          </View>
          <TouchableOpacity
            style={styles.optimizeButton}
            onPress={handleOptimize}
            disabled={isOptimizing}
            activeOpacity={0.8}
          >
            {isOptimizing ? (
              <ActivityIndicator color="#000" size="small" />
            ) : (
              <>
                <Sparkles color="#000" size={20} />
                <Text style={styles.optimizeButtonText}>
                  {optimizations.length > 0 ? 'Re-analyze' : 'Optimize'}
                </Text>
              </>
            )}
          </TouchableOpacity>
        </View>

        <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
          {isOptimizing && (
            <View style={styles.loadingCard}>
              <ActivityIndicator size="large" color="#FFFFFF" />
              <Text style={styles.loadingTitle}>Analyzing Your Finances</Text>
              <Text style={styles.loadingText}>
                Our AI is examining your spending patterns, income, and goals to generate personalized recommendations...
              </Text>
              <View style={styles.loadingSteps}>
                <View style={styles.loadingStep}>
                  <CheckCircle color={AppColors.success} size={16} />
                  <Text style={styles.loadingStepText}>Analyzing transactions</Text>
                </View>
                <View style={styles.loadingStep}>
                  <CheckCircle color={AppColors.success} size={16} />
                  <Text style={styles.loadingStepText}>Identifying patterns</Text>
                </View>
                <View style={styles.loadingStep}>
                  <ActivityIndicator size="small" color="#FFFFFF" />
                  <Text style={styles.loadingStepText}>Generating recommendations</Text>
                </View>
              </View>
            </View>
          )}

          {report && !isOptimizing && (
            <View style={styles.summaryCard}>
              <LinearGradient
                  colors={['#18181B', '#09090B']}
                  style={StyleSheet.absoluteFill}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 1 }}
              />
              <View style={styles.summaryHeader}>
                <Zap color="#F59E0B" size={28} fill="#F59E0B" />
                <View style={{ flex: 1 }}>
                  <Text style={styles.summaryTitle}>Your Optimization Plan</Text>
                  <Text style={styles.summarySubtitle}>AI-generated recommendations</Text>
                </View>
              </View>
              <View style={styles.summaryMetrics}>
                <View style={styles.summaryMetric}>
                  <TrendingDown color={AppColors.success} size={24} />
                  <Text style={styles.summaryMetricLabel}>Monthly Savings</Text>
                  <Text style={[styles.summaryMetricValue, { color: AppColors.success }]}>
                    JD {report.totalSavings.toFixed(0)}
                  </Text>
                </View>
                <View style={styles.summaryDivider} />
                <View style={styles.summaryMetric}>
                  <TrendingUp color="#FFFFFF" size={24} />
                  <Text style={styles.summaryMetricLabel}>Income Growth</Text>
                  <Text style={[styles.summaryMetricValue, { color: '#FFFFFF' }]}>
                    JD {report.totalIncome.toFixed(0)}
                  </Text>
                </View>
              </View>
              <View style={styles.summaryTotal}>
                <Text style={styles.summaryTotalLabel}>Total Monthly Impact</Text>
                <Text style={styles.summaryTotalValue}>
                  +JD {(report.totalSavings + report.totalIncome).toFixed(0)}
                </Text>
                <Text style={styles.summaryTotalSubtext}>
                  That&apos;s JD {((report.totalSavings + report.totalIncome) * 12).toFixed(0)} per year!
                </Text>
              </View>
            </View>
          )}

          {optimizations.length === 0 && !isOptimizing ? (
            <View style={styles.emptyState}>
              <View style={styles.emptyIconContainer}>
                <Sparkles color="#FFFFFF" size={48} />
              </View>
              <Text style={styles.emptyTitle}>Ready to Optimize?</Text>
              <Text style={styles.emptyText}>
                Get personalized AI-powered recommendations to reduce expenses and increase your income
              </Text>
              <TouchableOpacity style={styles.emptyButton} onPress={handleOptimize}>
                <Text style={styles.emptyButtonText}>Generate Recommendations</Text>
              </TouchableOpacity>
            </View>
          ) : null}

          {expenseReductions.length > 0 && (
            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <TrendingDown color={AppColors.success} size={24} />
                <Text style={styles.sectionTitle}>Expense Reduction</Text>
              </View>
              {expenseReductions.map(suggestion => (
                <OptimizationCard
                  key={suggestion.id}
                  suggestion={suggestion}
                  isExpanded={expandedIds.has(suggestion.id)}
                  onToggle={() => toggleExpand(suggestion.id)}
                  onMarkImplemented={() => handleMarkImplemented(suggestion.id)}
                />
              ))}
            </View>
          )}

          {incomeIncreases.length > 0 && (
            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <TrendingUp color="#FFFFFF" size={24} />
                <Text style={styles.sectionTitle}>Income Opportunities</Text>
              </View>
              {incomeIncreases.map(suggestion => (
                <OptimizationCard
                  key={suggestion.id}
                  suggestion={suggestion}
                  isExpanded={expandedIds.has(suggestion.id)}
                  onToggle={() => toggleExpand(suggestion.id)}
                  onMarkImplemented={() => handleMarkImplemented(suggestion.id)}
                />
              ))}
            </View>
          )}

          {savingsBoosts.length > 0 && (
            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <Target color="#A1A1AA" size={24} />
                <Text style={styles.sectionTitle}>Savings Boost</Text>
              </View>
              {savingsBoosts.map(suggestion => (
                <OptimizationCard
                  key={suggestion.id}
                  suggestion={suggestion}
                  isExpanded={expandedIds.has(suggestion.id)}
                  onToggle={() => toggleExpand(suggestion.id)}
                  onMarkImplemented={() => handleMarkImplemented(suggestion.id)}
                />
              ))}
            </View>
          )}

          {investments.length > 0 && (
            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <Sparkles color={AppColors.warning} size={24} />
                <Text style={styles.sectionTitle}>Investment Opportunities</Text>
              </View>
              {investments.map(suggestion => (
                <OptimizationCard
                  key={suggestion.id}
                  suggestion={suggestion}
                  isExpanded={expandedIds.has(suggestion.id)}
                  onToggle={() => toggleExpand(suggestion.id)}
                  onMarkImplemented={() => handleMarkImplemented(suggestion.id)}
                />
              ))}
            </View>
          )}
          <View style={{ height: 100 }} />
        </ScrollView>
      </View>
    </View>
  );
}

function OptimizationCard({
  suggestion,
  isExpanded,
  onToggle,
  onMarkImplemented,
}: {
  suggestion: OptimizationSuggestion;
  isExpanded: boolean;
  onToggle: () => void;
  onMarkImplemented: () => void;
}) {
  const priorityColor = suggestion.priority === 'high' 
    ? AppColors.danger 
    : suggestion.priority === 'medium' 
    ? AppColors.warning 
    : '#A1A1AA';

  const difficultyColor = suggestion.implementationDifficulty === 'easy'
    ? AppColors.success
    : suggestion.implementationDifficulty === 'moderate'
    ? AppColors.warning
    : AppColors.danger;

  return (
    <TouchableOpacity
      style={[styles.card, suggestion.implemented && styles.cardImplemented]}
      onPress={onToggle}
      activeOpacity={0.7}
    >
      <View style={styles.cardHeader}>
        <View style={styles.cardHeaderLeft}>
          {suggestion.implemented ? (
            <CheckCircle color={AppColors.success} size={24} />
          ) : (
            <Circle color={priorityColor} size={24} />
          )}
          <View style={styles.cardHeaderText}>
            <Text style={[styles.cardTitle, suggestion.implemented && styles.cardTitleImplemented]}>
              {suggestion.title}
            </Text>
            <View style={styles.cardMeta}>
              <View style={[styles.priorityBadge, { backgroundColor: `${priorityColor}20` }]}>
                <Text style={[styles.priorityBadgeText, { color: priorityColor }]}>
                  {suggestion.priority.toUpperCase()}
                </Text>
              </View>
              {suggestion.potentialSavings && suggestion.potentialSavings > 0 && (
                <View style={styles.savingsBadge}>
                  <TrendingDown color={AppColors.success} size={14} />
                  <Text style={styles.savingsBadgeText}>
                    JD {suggestion.potentialSavings.toFixed(0)}
                  </Text>
                </View>
              )}
              {suggestion.potentialIncome && suggestion.potentialIncome > 0 && (
                <View style={styles.incomeBadge}>
                  <TrendingUp color="#FFFFFF" size={14} />
                  <Text style={styles.incomeBadgeText}>
                    JD {suggestion.potentialIncome.toFixed(0)}
                  </Text>
                </View>
              )}
            </View>
          </View>
        </View>
      </View>

      <Text style={styles.cardDescription}>{suggestion.description}</Text>

      {isExpanded && (
        <View style={styles.cardExpanded}>
          <View style={styles.cardMetaRow}>
            <View style={styles.cardMetaItem}>
              <Clock color="#A1A1AA" size={16} />
              <Text style={styles.cardMetaText}>{suggestion.timeframe}</Text>
            </View>
            <View style={styles.cardMetaItem}>
              <AlertCircle color={difficultyColor} size={16} />
              <Text style={[styles.cardMetaText, { color: difficultyColor }]}>
                {suggestion.implementationDifficulty.charAt(0).toUpperCase() + 
                 suggestion.implementationDifficulty.slice(1)}
              </Text>
            </View>
          </View>

          <View style={styles.actionItemsContainer}>
            <Text style={styles.actionItemsTitle}>Action Steps:</Text>
            {suggestion.actionItems.map((item, index) => (
              <View key={index} style={styles.actionItem}>
                <View style={styles.actionItemBullet} />
                <Text style={styles.actionItemText}>{item}</Text>
              </View>
            ))}
          </View>

          {!suggestion.implemented && (
            <TouchableOpacity
              style={styles.implementButton}
              onPress={onMarkImplemented}
              activeOpacity={0.8}
            >
              <CheckCircle color="#000" size={20} />
              <Text style={styles.implementButtonText}>Mark as Implemented</Text>
            </TouchableOpacity>
          )}
        </View>
      )}
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  contentContainer: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerTitle: {
    fontFamily: fontFamily,
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontFamily: fontFamily,
    fontSize: 14,
    color: '#A1A1AA',
  },
  optimizeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
  },
  optimizeButtonText: {
    fontFamily: fontFamily,
    color: '#000000',
    fontSize: 15,
    fontWeight: '700',
  },
  content: {
    flex: 1,
  },
  summaryCard: {
    margin: 20,
    marginBottom: 0,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  summaryTitle: {
    fontFamily: fontFamily,
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  summaryMetrics: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  summaryMetric: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  summaryMetricLabel: {
    fontFamily: fontFamily,
    fontSize: 12,
    color: '#A1A1AA',
    textAlign: 'center',
  },
  summaryMetricValue: {
    fontFamily: fontFamily,
    fontSize: 20,
    fontWeight: '700',
  },
  summaryDivider: {
    width: 1,
    backgroundColor: '#333',
    marginHorizontal: 16,
  },
  summarySubtitle: {
    fontFamily: fontFamily,
    fontSize: 12,
    color: '#A1A1AA',
    marginTop: 2,
  },
  summaryTotal: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  summaryTotalLabel: {
    fontFamily: fontFamily,
    fontSize: 14,
    color: '#A1A1AA',
    marginBottom: 6,
  },
  summaryTotalValue: {
    fontFamily: fontFamily,
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  summaryTotalSubtext: {
    fontFamily: fontFamily,
    fontSize: 12,
    color: '#A1A1AA',
    marginTop: 6,
  },
  loadingCard: {
    backgroundColor: '#18181B',
    margin: 20,
    marginBottom: 0,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  loadingTitle: {
    fontFamily: fontFamily,
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 16,
    marginBottom: 8,
  },
  loadingText: {
    fontFamily: fontFamily,
    fontSize: 14,
    color: '#A1A1AA',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  loadingSteps: {
    alignSelf: 'stretch',
    gap: 12,
  },
  loadingStep: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  loadingStepText: {
    fontFamily: fontFamily,
    fontSize: 14,
    color: '#A1A1AA',
  },
  emptyState: {
    alignItems: 'center',
    padding: 40,
    margin: 20,
    backgroundColor: '#18181B',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#333',
  },
  emptyIconContainer: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#27272A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emptyTitle: {
    fontFamily: fontFamily,
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  emptyText: {
    fontFamily: fontFamily,
    fontSize: 15,
    color: '#A1A1AA',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  emptyButton: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 24,
  },
  emptyButtonText: {
    fontFamily: fontFamily,
    color: '#000000',
    fontSize: 16,
    fontWeight: '700',
  },
  section: {
    padding: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: fontFamily,
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: '#18181B',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  cardImplemented: {
    opacity: 0.7,
    backgroundColor: '#18181B',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    gap: 12,
    flex: 1,
  },
  cardHeaderText: {
    flex: 1,
  },
  cardTitle: {
    fontFamily: fontFamily,
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  cardTitleImplemented: {
    textDecorationLine: 'line-through',
  },
  cardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  priorityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  priorityBadgeText: {
    fontFamily: fontFamily,
    fontSize: 10,
    fontWeight: '700',
  },
  savingsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  savingsBadgeText: {
    fontFamily: fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: AppColors.success,
  },
  incomeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  incomeBadgeText: {
    fontFamily: fontFamily,
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  cardDescription: {
    fontFamily: fontFamily,
    fontSize: 14,
    color: '#A1A1AA',
    lineHeight: 20,
  },
  cardExpanded: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  cardMetaRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  cardMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cardMetaText: {
    fontFamily: fontFamily,
    fontSize: 13,
    color: '#A1A1AA',
  },
  actionItemsContainer: {
    marginBottom: 16,
  },
  actionItemsTitle: {
    fontFamily: fontFamily,
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 8,
  },
  actionItemBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
    marginTop: 6,
  },
  actionItemText: {
    fontFamily: fontFamily,
    flex: 1,
    fontSize: 13,
    color: '#A1A1AA',
    lineHeight: 18,
  },
  implementButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    borderRadius: 12,
  },
  implementButtonText: {
    fontFamily: fontFamily,
    color: '#000000',
    fontSize: 15,
    fontWeight: '700',
  },
});
